wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1671696003.576403
    t:
      1:
      - 5
      - 30
      - 53
      - 55
      2:
      - 5
      - 30
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.10.8
      5: 0.13.7
      8:
      - 5
dataset:
  desc: null
  value: MoteStrain
delta:
  desc: null
  value: 1
lambda1:
  desc: null
  value: 20
lambda2:
  desc: null
  value: 0.1
m:
  desc: null
  value: 0.8
noise_ratio:
  desc: null
  value: 0.2
seed:
  desc: null
  value: 42
test:
  desc: null
  value: false
